(in-package #:org.shirakumo.alloy.examples)

(define-example clipping (screen)
  (let* ((window (windowing:make-window screen :min-size (alloy:px-size 640 480)))
         (focus (make-instance 'alloy:visual-focus-manager :focus-parent window))
         (border (make-instance 'alloy:border-layout :layout-parent window))
         (clip (make-instance 'alloy:clip-view :layout-parent border :limit :x))
         (scroll (alloy:represent-with 'alloy:y-scrollbar clip))
         (layout (make-instance 'alloy:vertical-linear-layout :layout-parent clip)))
    (alloy:enter scroll border :place :east)
    (dotimes (i 5)
      (alloy:represent "Group" 'alloy:button :layout-parent layout :focus-parent focus)
      (let ((layout (make-instance 'alloy:grid-layout :col-sizes '(200 T) :row-sizes '(50)
                                                      :layout-parent layout)))
        (dotimes (i 20)
          (alloy:enter "Item" layout))))))
