(in-package #:org.shirakumo.alloy.examples)

(define-example simple-window (screen)
  (let* ((window (windowing:make-window screen))
         (focus (make-instance 'alloy:focus-list :focus-parent window))
         (layout (make-instance 'alloy:vertical-linear-layout :layout-parent window))
         (name "")
         (button (alloy:represent "Greet" 'alloy:button)))
    (alloy:represent name 'alloy:input-line :focus-parent focus :layout-parent layout)
    (alloy:enter button layout)
    (alloy:enter button focus)
    (alloy:on alloy:activate (button)
      (let ((window (windowing:make-window screen :background-color colors:white)))
        (alloy:enter (make-instance 'alloy:label* :value (format NIL "Hello, ~a!" name)) window)))))

(define-example combo (screen)
  (let* ((window (windowing:make-window screen))
         (focus (make-instance 'alloy:focus-list :focus-parent window))
         (layout (make-instance 'alloy:vertical-linear-layout :layout-parent window))
         (selection NIL)
         (value 0f0)
         (combo (alloy:represent selection 'alloy:combo-set :value-set '(NIL :a :b :c :d :e :f :g :h :i :j :k :l :m :n :o :p :q :r :s :t :u :v :w :x :y :z)))
         (slider (alloy:represent value 'alloy:ranged-slider))
         (button (alloy:represent "Confirm" 'alloy:button)))
    (alloy:enter combo layout)
    (alloy:enter slider layout)
    (alloy:enter button layout)
    (alloy:enter combo focus)
    (alloy:enter slider focus)
    (alloy:enter button focus)))
